[![Build](https://github.com/renovatebot/renovate/actions/workflows/build.yml/badge.svg)](https://github.com/renovatebot/renovate/actions/workflows/build.yml)[![Build](https://github.com/renovatebot/renovate/actions/workflows/build.yml/badge.svg)](https://github.com/renovatebot/renovate/actions/workflows/build.yml)<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>libraries-bom</artifactId>
      <version>26.59.0</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>com.google.cloud:google-cloud-bigqueryconnection</artifactId>
  </dependency>
</dependencies>      "resolved": "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz",

-{
}
}
<p>
[link]-[Bot] # To get started with Dependabot version update [AUTOTITLE]
> # package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://github.com/tr4200812/-tr4200812/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 3
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
}}
